CREATE TABLE "PRUEBA"."TITULAR" 
   ("TITULAR_ID" NUMBER, 
		"TITULAR_NOMBRE" VARCHAR2(1000), 
		"TITULAR_CEDULA" VARCHAR2(100), 
		"TITULAR_TELEFONO" VARCHAR2(100), 
		 CONSTRAINT "TITULAR_PK" PRIMARY KEY ("TITULAR_ID") ENABLE
   );

CREATE TABLE "PRUEBA"."TARJETA" 
   (	"TARJETA_ID" NUMBER, 
			"TARJETA_NUMERO_VALIDACION" VARCHAR2(100), 
			"TARJETA_PAN" VARCHAR2(100), 
			"TARJETA_ESTADO" VARCHAR2(100), 
			"TARJETA_TITULAR" NUMBER, 
			"TARJETA_TIPO" VARCHAR2(100), 
			 CONSTRAINT "TARJETA_PK" PRIMARY KEY ("TARJETA_ID") ENABLE, 
			 CONSTRAINT "FK_TITULAR" FOREIGN KEY ("TARJETA_ID") REFERENCES "PRUEBA"."TITULAR" ("TITULAR_ID") ENABLE
   );

CREATE TABLE "PRUEBA"."TRANSACCION" 
   (	"TRANSACCION_ID" NUMBER, 
			"TRANSACCION_TARJETA" NUMBER, 
			"TRANSACCION_REFERENCIA" VARCHAR2(100), 
			"TRANSACCION_VALOR" NUMBER, 
			"TRANSACCION_DIRECCION" VARCHAR2(100), 
			 CONSTRAINT "TRANSACCION_PK" PRIMARY KEY ("TRANSACCION_ID") ENABLE, 
			 CONSTRAINT "FK_TARJETA" FOREIGN KEY ("TRANSACCION_TARJETA") REFERENCES "PRUEBA"."TARJETA" ("TARJETA_ID") ENABLE
   ) ;